### ISSUE TITLE
Sometime, AU app shows connection timeout

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2860]
Sometime, AU app shows connection timeout about Feed event. We need your help to check in client app, @phuocbitmark. And we also need your help to check in server, @hxw. 
Thank you
[feed connection timeout.txt](https://github.com/bitmark-inc/autonomy-apps/files/12341776/feed.connection.timeout.txt)

**Comment by hxw** [comment]
Looking at the log  line 1631:
```
2023-08-15 11:11:16.674496: [INFO] App: [BackgroundService] taskId: com.bitmark.autonomywallet.notification
2023-08-15 11:11:17.003051: [INFO] App: [SettingsDataService][Done] restoreSettingsData
2023-08-15 13:21:10.448534: [INFO] App: [FeedFollowService] Instance of 'FetchFeedsSuccess'
2023-08-15 13:21:10.448702: [INFO] App: [FeedService] 0 unread feeds
2023-08-15 13:21:10.448720: [INFO] App: [FeedFollowService] Instance of 'FetchFeedsSuccess'
2023-08-15 13:21:10.448740: [INFO] App: [FeedService] 0 unread feeds
2023-08-15 13:21:10.448751: [INFO] App: [FeedFollowService] Instance of 'FetchFeedsFailure'
2023-08-15 13:21:10.448857: [WARNING] App: Unhandled error: DioError [DioErrorType.connectTimeout]: Connecting timed out [0ms]
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      _FeedApi.getFeeds (package:autonomy_flutter/gateway/feed_api.g.dart:117)
#2      FeedServiceImpl._fetchFeeds (package:autonomy_flutter/service/feed_service.dart:423)
#3      FeedServiceImpl._handleMessageInIsolate (package:autonomy_flutter/service/feed_service.dart:326)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#8      _StreamController._add (dart:async/stream_controller.dart:648)
#9      _StreamController.add (dart:async/stream_controller.dart:596)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

not sure what API is being called for the above error. Is the client really trying to connect 3 times to feed server within a few microseconds?

---

line 1666:  (maybe client has closed the socket because of the timeout above?)
```
2023-08-15 13:21:10.448992: [INFO] App: NavigationService.showErrorDialog
2023-08-15 13:21:10.449365: [INFO] App: [FeedFollowService] Instance of 'FetchFeedsSuccess'
2023-08-15 13:21:10.449383: [INFO] App: [FeedService] 0 unread feeds
2023-08-15 13:21:10.449405: [INFO] App: [FeedFollowService] Instance of 'FetchFeedsFailure'
2023-08-15 13:21:10.449458: [WARNING] App: Unhandled error: DioError [DioErrorType.other]: HttpException: Connection closed while receiving data, uri = https://feed.autonomy.io/v1/feed/?testnet=false&count=50
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      _FeedApi.getFeeds (package:autonomy_flutter/gateway/feed_api.g.dart:117)
#2      FeedServiceImpl._fetchFeeds (package:autonomy_flutter/service/feed_service.dart:423)
#3      FeedServiceImpl._handleMessageInIsolate (package:autonomy_flutter/service/feed_service.dart:326)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#8      _StreamController._add (dart:async/stream_controller.dart:648)
#9      _StreamController.add (dart:async/stream_controller.dart:596)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

---

Also customer support connection has problems, line 1710:
```
2023-08-15 13:21:10.616048: [INFO] API: API Request: $ curl -i\
	-X GET\
	-H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTIxNTkwNzYsImp0aSI6IjMyNTFlMTk3LTQ2MzAtNDgzYS05MDYxLWVkZGFjZjg3YzBiYyIsImlhdCI6MTY5MjA3MjY3Niwic3ViIjoiZGlkOmtleTp6UTNzaHZSaFh2REcyU3dZSjNVb0hlUXlmZVp1OTlkRnNvd0w5Mm5oN29xSkFTNVlEIiwicGxhbiI6Im5vbmUiLCJ0cmlhbCI6ZmFsc2UsInBlcm1pc3Npb24iOiJmdWxsIn0.skZndfG6tIWUem2y_710qnaq1P-r3Vf0ggljROPAJu0GsYqQMWdtrXqGyGc8iI683XyQHmhb8Nkr4kkSuiieX40WTQKkN4TQVF7JBblLI4t27aw3u9t9IvgZHNDbbcTw5ORtaTVNuee-up6Tbk2QZz1CmvLN8OxWt1zoJU9yzXuyRiV0US1fPmYpN4zAK3LZ23j7GGvHb-vSrukv1Y-XDcW6OOEK2FjAyVQhjMxBMIZtMEvD2iITb0H_BWmBM5ry7dsliv5Vp2bTA-aHa1623d2KAxnhOjLmMqh3Hqc6SHjW0B1zy9iXO2YjHKU6D5TQytv4vgbgwFJUBniYUeA_GUgnjI3g1xuJN_AXFq3MFIlAJfqolmKqlXiKWrtkAlhaSEn4QeNG9S-rO4W9Zm7lkCowVH0yxOj8MNaKm0og9Lj42J9Kpq21uyipQxWAE-0PHFk7VlBAaJDFrsrPqiRKr_iHz59RmVSO078EEQjFYrrMHp-Sckj5SiOxG-ZSuEcBelG6SfOtkTjSvLhgzNaCH_vcuci275uqVHE8pKSNipCMwpZR5mD0TkftrOGMHcrMnrG8rbVIACKhS2VykDkZ0zfmsgCLEh0TfMtTw-ITmh3iBNksQhw7bcqPn1_j4gkYxTt8_diBqFyZRUW31rCXg-EGuluEJfPwzTtyR0b3gFQ"\
	-d "{}"\
	"https://support.autonomy.io/v1/issues"
2023-08-15 13:21:10.616073: [WARNING] API: Respond error: Connecting timed out [10000ms]
2023-08-15 13:21:10.618466: [WARNING] App: Unhandled error: DioError [DioErrorType.connectTimeout]: Connecting timed out [10000ms]
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      _CustomerSupportApi.getIssues (package:autonomy_flutter/gateway/customer_support_api.g.dart:28)
#2      CustomerSupportServiceImpl.getIssues (package:autonomy_flutter/service/customer_support_service.dart:145)
#3      CustomerSupportServiceImpl.getIssuesAndAnnouncement (package:autonomy_flutter/service/customer_support_service.dart:532)
#4      _HomeNavigationPageState.initState (package:autonomy_flutter/screen/home/home_navigation_page.dart:195)
```

---

It seems unlikely that both services would be having the same problem at exactly the same time within some 200ms. This would indicate some kind of network disconnect; like WIFI → Cell transition. Though it could be some other part of the network that was down.

(e.g., On Android, after rebooting WIFI router, I have had the phone lose connection until I manually reconnect or move out of WIFI range to force Cell data switch.)

**Comment by phuocbitmark** [comment]
@hxw _FeedApi.getFeeds => /v1/feed
